require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - vendor/bundle/**/*

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 10
