require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - vendor/bundle/**/*

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 15
